server:
  port: 8080 #配置程序端口，默认为8080
  context-path: /caas # 配置默认访问路径

#flow
flow_rule_project: com.allmsi.plugin.flow.service.impl.FlowRulePjImpl

#file
file_md5_unique: false
upload_file_path: /var/tmp/caas
chunked_temp_path: /chunked/temp
download_url: /file/download?id=
#open 
path: 
expiry_date: 7
open_path: /open
tCount: 7
file: com.allmsi.plugin.open.service.impl.OpenFileServiceImpl

im:
  session:
    out: 3600 #session out time
  user:
    default:
      psw: 1234 #用户的默认密码
  cache: redis      #Cache configuration item,可选缓存map,redis,默认map,严格匹配
  redis:
    cache: com.allmsi.cache.redis.RedisCache  #redis实现类
    
spring: 
  datasource:
    url: jdbc:mysql://47.105.38.33:3306/im_mis_platform_dev?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=CST
    username: im01
    password: im123456
    driver-class-name: com.mysql.jdbc.Driver
  redis: 
    database: 1
    host: 47.105.38.33
    port: 6379
    password: im123456
    timeout: 5000
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
mybatis:
  mapperLocations: classpath:mapper/*.xml,classpath:aurhMapper/*.xml,classpath:flowMapper/*.xml
  typeAliasesPackage: com.allmsi.mis.model.po,com.allmsi.auth.model.po,com.allmsi.flow.model
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
MENU_1: [{"id": 1,"path": "/project","name": "\u9879\u76EE\u7BA1\u7406","icon": "object-group","children": [{"id": 11,"path": "/edit","name": "\u9879\u76EE\u7ACB\u9879","icon": "edit"}, {"id": 12,"path": "/list","name": "\u5F85\u529E\u9879\u76EE","icon": "list-ol"}, {"id": 13,"path": "/mylist","name": "\u9879\u76EE\u5217\u8868","icon": "list-alt"}]}]
MENU_2: [{"id": 1,"path": "/project","name": "\u9879\u76EE\u7BA1\u7406","icon": "object-group","children": [{"id": 11,"path": "/edit","name": "\u9879\u76EE\u7ACB\u9879","icon": "edit"}, {"id": 12,"path": "/list","name": "\u5F85\u529E\u9879\u76EE","icon": "list-ol"}, {"id": 13,"path": "/mylist","name": "\u9879\u76EE\u5217\u8868","icon": "list-alt"}, {"id": 14,"path": "/relist","name": "\u8DDF\u8FDB\u9879\u76EE","icon": "list-alt"}]}, {"id": 2,"path": "/customer","name": "\u5BA2\u6237\u7BA1\u7406","icon": "users","children": [{"id": 21,"path": "/zlist","name": "\u6CE8\u518C\u7533\u8BF7\u5217\u8868","icon": "server"}, {"id": 22,"path": "/ulist/1","name": "\u5185\u5BB9\u7528\u6237","icon": "list"}, {"id": 23,"path": "/ulist/3","name": "\u5A92\u4F53\u7528\u6237","icon": "list-ul"}]}]
MENU_3: [{"id": 1,"path": "/project","name": "\u9879\u76EE\u7BA1\u7406","icon": "object-group","children": [{"id": 12,"path": "/list","name": "\u5F85\u529E\u9879\u76EE","icon": "list-ol"}, {"id": 13,"path": "/mylist","name": "\u9879\u76EE\u5217\u8868","icon": "list-alt"}]}]